### ISSUE TITLE
A question: Repository pattern and Bulk Insert

### ISSUE THREAD

**Issue by afshany** [tiagoln/BulkExtensions#21]
I am not sure if I can use bulk insert in repository pattern?

thanks,
-Shany

**Comment by tiagoln** [comment]
I do use it in a project with repository pattern. I think you should try to work it out, and if you have any issue I'll be glad to help.

**Comment by afshany** [comment]
I added DbContext.BulkInsertOrUpdate to the generic Repository and called it in builder class. How about BeginTransaction. where can It be added to or called from? 

Thanks

**Comment by afshany** [comment]
I don't want to commit changes for one repository. Is there any function with out context.commit() at the end which does the repository.add and I can do saveChanges at the end?

**Comment by tiagoln** [comment]
> I don't see the point of Transaction when you commit changes to DB in BulkInsert!

Actually that's not true, If you begin your own transaction by calling `context.BeginTransaction()` anywhere in your code, the library will use your transaction and will NOT commit at the end, the line of code in the BulkOperation class that calls `context.Commit()` checks if you are managing your own transactions, the `context` object in this line is not `DbContext`, it is in fact an object of type [`DbContexWrapper`,](https://github.com/tiagoln/BulkExtensions/blob/master/BulkExtensions.Shared/Context/DbContextWrapper.cs) an abstraction I use to deal with connections and transactions related stuff.

The `Commit()` method body of the `DbContexWrapper` class only Commits the transaction if it is an internal one, not created by you, it is done this way because if you do not create you own transactions I need to create internal ones for the scope of the operation to prevent inconsistent data to be persisted in case of any error:

`Commit()` method body:
```
public void Commit()
        {
            if (IsInternalTransaction)
            {
                Transaction.Commit();
                Transaction.Dispose();
            }
        }
```

**Comment by afshan3** [comment]
Thanks! It works as explained.

**Comment by tiagoln** [comment]
You're welcome. =D
