### ISSUE TITLE
Bulk insert or update

### ISSUE THREAD

**Issue by chinarosesz** [tiagoln/BulkExtensions#4]
Is it possible that you can implement bulk insert or update?

**Comment by tiagoln** [comment]
It's one of the features I'm looking to implement. I intend to release a new version with this feature very soon.

**Comment by chinarosesz** [comment]
For now, I was thinking about calling an Insert and if it throws a duplicate key exception, I can catch it and then call BulkInsert, do you think this workaround will work for now? Ultimately, I can always write a long MERGE sql query, but would prefer to leverage entity framework extension as much as I can.

**Comment by tiagoln** [comment]
If you have a collection with both entities to insert and update the best workaround on this scenario would be to filter the collection by Id using Linq, since the entities that will be inserted do not have an Id yet, and the ones who needs to be updated have. Example:
`context.BulkUpdate(entities.Where(entity => entity.Id != 0));
 context.BulkInsert(entities.Where(entity => entity.Id == 0));
`
Update first, than insert, because this way you can populate the Ids on the BulkInsert command without passing them to the BulkUpdate, like this:
`context.BulkInsert(entities.Where(entity => entity.Id == 0), Identity.Output);`

Right now I'm almost done updating this library to work with EFCore, then I'll implement the InsertOrUpdate, it shouldn't take too long as the code is very similar to the BulkUpdate command.

**Comment by tiagoln** [comment]
I've released a new version with InsertOrUpdate feature, please check it out :)
